### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Tshobohwa** [Sonikak004/Bootstrap-Portfolio#2]
ISSUES FOUNDED
- Kindly remove the border radius of buttons and work divs by adding the class "rounded-0"
- Kindly add some responsiveness on the grid card.
- Kindly remove the direct child element div of the nav bar and add the following classes to the nav bar to fit the Figma design:
     - d-flex
     - justify-content-between
     - px-5

**Comment by clin2on3mun** [comment]
- The project is working great continue exploring more about bootstrap and adding other bootstrap CSS features
-

**Comment by Sonikak004** [comment]
Implemented suggested changes, Thank you 👍

**Comment by Sonikak004** [comment]
Implemented suggested changes, Thank you 👍
